import type { components } from './generated/schema'

type SchemaMap = components['schemas']

export type LoginRequest = SchemaMap['LoginRequest']
export type LoginResponse = SchemaMap['LoginResponse']
export type SessionResponse = SchemaMap['SessionResponse']
export type Refill = SchemaMap['Refill']
export type HeatDashboard = SchemaMap['HeatDashboard']
export type CreateRefillRequest = SchemaMap['CreateRefillRequest']
export type CaloriesDashboard = SchemaMap['CaloriesDashboard']
export type CalorieTarget = SchemaMap['CalorieTarget']
export type CreateCalorieLogRequest = SchemaMap['CreateCalorieLogRequest']
export type CalorieLog = SchemaMap['CalorieLog']
export type ExpensesDashboard = SchemaMap['ExpensesDashboard']
export type ExpensesSettings = SchemaMap['ExpensesSettings']
export type ExpensesSettingsView = SchemaMap['ExpensesSettingsView']
export type UpdateExpensesSettingsRequest = SchemaMap['UpdateExpensesSettingsRequest']
export type ExpenseChecklistItem = SchemaMap['ExpenseChecklistItem']
export type ExpenseEntry = SchemaMap['ExpenseEntry']
